services:

  dev:
    build:
      context: .
      dockerfile: docker/go.dev.Dockerfile
    container_name: grpc-sample-gateway-dev

    working_dir: /app

    networks:
      - grpc_sample_network

    volumes:
      - .:/app
      - go-gateway-cache:/go/pkg/mod

    ports:
      - "5000:5045"

    environment:
      - GOMODCACHE=/go/pkg/mod

volumes:
  go-gateway-cache:

networks:
  grpc_sample_network:
    external: true
    name: grpc_sample_network

