name: Deploy Grpc Sample Gateway

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev

env:
  IMAGE_NAME: "grpc-sample-gateway-prod"
  IMAGE_VERSION: "latest"
  IMAGE_NAME_TAR: "grpc-sample-gateway-prod.tar"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GATEWAY_PORT: 6000
      GRPC_TLS: false
      GRPC_REMOTE_SERVER: "localhost:8080"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create network traefik-network
        run: docker network create traefik-network || echo "Network traefik-network already exists"

      - name: Create .env.prod file
        run: |
          echo "GRPC_TLS=${{ env.GRPC_TLS }}" >> .env.prod
          echo "GRPC_REMOTE_SERVER=${{ env.GRPC_REMOTE_SERVER }}" >> .env.prod
          echo "GATEWAY_PORT=${{ env.GATEWAY_PORT }}" >> .env.prod

      - name: "Run Docker Compose Prod"
        run: |
          docker compose -f docker-compose.prod.yml up -d

      - name: Curl Http Endpoint
        run: curl http://localhost:${{ env.GATEWAY_PORT }}/doc/index.html

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: "Build Docker Image"
        run: |
          IMAGE_NAME="${{ env.IMAGE_NAME }}" IMAGE_VERSION="${{ env.IMAGE_VERSION }}" docker compose -f docker-compose.prod.yml build
          docker save ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} -o ${{ env.IMAGE_NAME_TAR }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: |
            docker-compose.prod.yml
            ${{ env.IMAGE_NAME_TAR }}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: [self-hosted, grpc-sample-gateway]

    environment: prod

    env:
      PATH_PROJECT: ${{ vars.PATH_PROJECT }}

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ env.PATH_PROJECT }}

      - name: Load Docker Image
        run: |
          cd ${{ env.PATH_PROJECT }}
          docker load -i ${{ env.IMAGE_NAME_TAR }}

      - name: List Docker images
        run: docker image ls

      - name: Run Production App with Docker Compose
        run: |
          cd ${{ env.PATH_PROJECT }} && echo $(pwd)
          IMAGE_NAME="${{ env.IMAGE_NAME }}" IMAGE_VERSION="${{ env.IMAGE_VERSION }}" docker compose -f docker-compose.prod.yml up -d

      - name: Cleanup unused Docker images
        run: docker image prune -af

      - name: List Docker images
        run: docker image ls

      - name: Remove tar file and List files in workspace
        run: |
          cd ${{ env.PATH_PROJECT }}
          rm ${{ env.IMAGE_NAME_TAR }} && ls -la

      - name: Check running containers
        run: docker ps -a

  check:
    if : false
    runs-on: [self-hosted, grpc-sample-gateway]

    environment: prod

    env:
      PATH_PROJECT: ${{ vars.PATH_PROJECT }}

    steps:
      - name: Check Whoami
        run: whoami

      - name: Enter to project directory
        run: cd ${{ env.PATH_PROJECT }} && echo $(pwd)

      - name: List files in project directory
        run: ls -la ${{ env.PATH_PROJECT }}

      - name: Curl Http Endpoint
        run: curl http://localhost:6000/doc/index.html
